project:
  type: website

website:
  title: "Austin's Blog"
  navbar:
    right:
      - href: about/index.qmd
        text: "About"
      - href: index.qmd
        text: "Posts"
      - href: notes/index.qmd
        text: "Notes"
  google-analytics: "G-DLC4C8LZFB"
format:
  html:
    theme:
      light: [default, style/custom_light.scss]
      dark:  [default, style/custom_dark.scss]
    toc: false
    toc-depth: 5
    toc-location: right
    grid:
        body-width: 610px
    mainfont: "Latin Modern"
    fontsize: 16px
    linestretch: 1.25
    html-math-method: mathjax
    highlight-style: github
    listing:
      table-hover: true
