project:
  type: website

website:
  title: "Austin's Blog"
  navbar:
    right:
      - href: about/index.qmd
        text: "About"
      - href: index.qmd
        text: "Posts"
      - href: notes/index.qmd
        text: "Notes"
  google-analytics: "G-DLC4C8LZFB"
format:
  html:
    theme:
      light: [default, style/custom_light.scss]
    grid:
        body-width: 600px
    fontsize: 14px
    # linestretch: 1.35
    toc: false
    toc-location: right
    html-math-method: mathjax
    highlight-style: github