project:
  type: website

website:
  title: "Austin's Blog"
  navbar:
    right:
      - href: ./about.qmd
        text: "About"
      - href: ./index.qmd
        text: "Posts"
      - href: ./notes.qmd
        text: "Notes"
  google-analytics: "G-DLC4C8LZFB"
  
format:
  html:
    theme: 
      light: [default, style.scss]
      dark: [default, style_dark.scss]
    respect-user-color-scheme: true
    grid:
        body-width: 600px
    mainfont: "Times"
    fontsize: 16px
    linestretch: 1.35
    toc: false
    toc-location: right
    html-math-method: mathjax
    highlight-style: github
