project:
  type: website

website:
  title: "Austin's Blog"
  navbar:
    right:
      - href: ./about.qmd
        text: "About"
      - href: ./posts.qmd
        text: "Posts"
      - href: ./notes.qmd
        text: "Notes"
  google-analytics: "G-DLC4C8LZFB"
format:
  html:
    theme:
      light: [litera, style/custom.scss]
    grid:
        body-width: 530px
    fontsize: 14.5px
    # linestretch: 1.35
    toc: false
    toc-location: right
    html-math-method: mathjax
    highlight-style: github